apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/vramk23/infrapub.git
    targetRevision: main
    path: cicd/tekton-pipelines
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
