apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-clusters-aws-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vramk23/infrapub.git
    targetRevision: main
    path: infra/crossplane/packages/k8s/aws
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
