apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-config
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/vramk23/infrapub.git
    targetRevision: main
    path: infra/clusters/dev/config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
