project: default

global:
  clusterConfigPath: infra/clusters/dev-test/cluster-configs

source:
  repoURL: https://github.com/vramk23/infrapub.git
  targetRevision: main
  
destination:
  server: https://kubernetes.default.svc
  namespace: crossplane

syncPolicy:
  CreateNamespace: true
  automated:
    prune: true
    selfHeal: true

compositions:
  - name: crossplane-aws-dev-k8s-packages
    path: infra/clusters/compositions/aws  

clusters:
  - name: dev-test
    configPath: infra/clusters/dev-test/cluster-configs
    defaultApps:
    - name: falco
      appConfigPath: infra/clusters/dev-test/app-configs/default-apps/falco-values.yaml
      repoURL: 'https://kube-tarian.github.io/helmrepo-supporting-tools'
      namespace: devfalco
      chart: falco
      targetRevision: "0.0.1"
    - name: kyverno
      appConfigPath: infra/clusters/dev-test/app-configs/default-apps/kyverno-values.yaml
      repoURL: 'https://kube-tarian.github.io/helmrepo-supporting-tools'
      namespace: devkyverno
      chart: kyverno
      targetRevision: "1.0.2"
    - name: prometheus
      appConfigPath: infra/clusters/dev-test/app-configs/default-apps/prometheus-values.yaml
      repoURL: 'https://kube-tarian.github.io/helmrepo-supporting-tools'
      namespace: devprometheus
      chart: kube-prometheus-stack
      targetRevision: "1.0.3"
    - name: promtail
      appConfigPath: infra/clusters/dev-test/app-configs/default-apps/promtail-values.yaml
      repoURL: 'https://kube-tarian.github.io/helmrepo-supporting-tools'
      namespace: devpromtail
      chart: promtail
      targetRevision: "1.0.0"
