project: default

source:
  repoURL: https://github.com/vramk23/infrapub.git
  targetRevision: main
  
destination:
  server: https://kubernetes.default.svc
  namespace: crossplane

syncPolicy:
  CreateNamespace: true
  automated:
    prune: true
    selfHeal: true

compositions:
  - name: crossplane-aws-dev-k8s-packages
    path: infra/clusters/compositions/aws  
  - name: crossplane-azure-dev-k8s-packages
    path: infra/clusters/compositions/azure
  - name: crossplane-gcp-dev-k8s-packages
    path: infra/clusters/compositions/gcp

clusters:
  - name: dev
    configPath: infra/clusters/dev/cluster-configs
    server: https://kubernetes.default.svc
    defaultApps:
    - name: dev-falco
      appConfigPath: infra/clusters/dev/app-configs/default-apps/falco-values.yaml
      repoURL: 'https://github.com/kube-tarian/helmrepo-supporting-tools.git'
      namespace: falco
      chart: falco
      targetRevision: "0.0.1"
    - name: dev-kyverno
      appConfigPath: infra/clusters/dev/app-configs/default-apps/kyverno-values.yaml
      repoURL: 'https://github.com/kube-tarian/helmrepo-supporting-tools.git'
      namespace: kyverno
      chart: kyverno
      targetRevision: "1.0.2"
    - name: dev-prometheus
      appConfigPath: infra/clusters/dev/app-configs/default-apps/prometheus-values.yaml
      repoURL: 'https://github.com/kube-tarian/helmrepo-supporting-tools.git'
      namespace: prometheus
      chart: kube-prometheus-stack
      targetRevision: "1.0.3"
    - name: dev-promtail
      appConfigPath: infra/clusters/dev/app-configs/default-apps/promtail-values.yaml
      repoURL: 'https://github.com/kube-tarian/helmrepo-supporting-tools.git'
      namespace: promtail
      chart: promtail
      targetRevision: "1.0.0"

  - name: prod
    configPath: infra/clusters/prod/clusterconfigs
    server: https://kubernetes.default.svc
    defaultApps:
    - name: prod-falco
      appConfigPath: infra/clusters/prod/app-configs/default-apps/falco-values.yaml
      repoURL: 'https://github.com/kube-tarian/helmrepo-supporting-tools.git'
      namespace: falco
      chart: falco
      targetRevision: "0.0.1"
    - name: prod-kyverno
      appConfigPath: infra/clusters/prod/app-configs/default-apps/kyverno-values.yaml
      repoURL: 'https://github.com/kube-tarian/helmrepo-supporting-tools.git'
      namespace: kyverno
      chart: kyverno
      targetRevision: "1.0.2"
    - name: prod-prometheus
      appConfigPath: infra/clusters/prod/app-configs/default-apps/prometheus-values.yaml
      repoURL: 'https://github.com/kube-tarian/helmrepo-supporting-tools.git'
      namespace: prometheus
      chart: kube-prometheus-stack
      targetRevision: "1.0.3"
    - name: prod-promtail
      appConfigPath: infra/clusters/prod/app-configs/default-apps/promtail-values.yaml
      repoURL: 'https://github.com/kube-tarian/helmrepo-supporting-tools.git'
      namespace: promtail
      chart: promtail
      targetRevision: "1.0.0"
