apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/vramk23/infrapub.git
    targetRevision: main
    path: infra/crossplane/crossplane-config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
